version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: workspace
        container_name: workspace
        ports:
            - "8020:80"
        volumes:
            - ./:/var/www/html
        networks:
            - lab2-network
        depends_on:
            - db
    db:
        image: 'mysql:latest'
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./.docker/db_data:/var/lib/mysql
            - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - lab2-network
    composer:
        image: composer:latest
        container_name: composer
        command: composer install
        volumes:
            - ./:/app
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - 8021:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - lab2-network

networks:
    lab2-network:
